apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wjmdhw6w2-go
  janus-idp.io/tekton: wjmdhw6w2-go
  backstage.io/kubernetes-id: wjmdhw6w2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wjmdhw6w2-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
